### ISSUE TITLE
'charmap' codec can't encode characters in position 22-24: character maps to <undefined> Chronostasis IN

### ISSUE THREAD

**Issue by MaximIce1** [kvarenzn/phisap#60]
https://i.imgur.com/07Mkdy3.png

**Comment by MaximIce1** [comment]
https://user-images.githubusercontent.com/79106345/234696591-6ee77dcb-5773-47f7-b822-669870268eea.mp4

**Comment by kvarenzn** [comment]
I've googled this problem, and it might be a problem related to your character encoding settings. phisap will output UTF-8 Chinese characters in the terminal, and I guess your current terminal codepage is not UTF-8, so that causes this problem.
However, I'm sorry that I don't have any plans to add multi-language support for phisap for now, but I would be glad if anyone could help me complete that.

A temporary solution for this is to run `chcp 65001` to set your terminal's codepage to `UTF-8` before running phisap.

(The following is the original Chinese text, if the English translation is wrong, please refer to the Chinese version)

我搜了一下，这应该是跟语言文字编码相关的问题。phisap会在终端中输出UTF-8中文字符，我猜你目前终端的codepage应该不是UTF-8，所以导致了这种错误。如果可以的话，请贴一下运行命令`chcp`之后的命令行输出。
不过，很抱歉我暂时没有为phisap添加多语言支持的计划，当然如果你愿意帮助我完成多语言的支持，那么我非常欢迎。

一个临时的解决方案是，在运行phisap之前，先运行`chcp 65001`将你的终端的codepage设置为`UTF-8`。

**Comment by MaximIce1** [comment]
Worked, thanks
